[window]
decorations = "Full"
opacity = 0.9
padding = { x = 12, y = 3 }
startup_mode = "Maximized"
dynamic_padding = true
blur = true

[shell]
    program = "wsl.exe ~"

[font]
normal.family = "Hack Nerd Font Mono"
offset.y = 6
glyph_offset.x = 0
glyph_offset.y = 3

size = 12

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'

foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'

yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'

blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
